In [19]:
import torch
import os

from minerva.models.nets.time_series.gans import TTSGAN_Generator, TTSGAN_Discriminator, TTSGAN_Encoder, GAN

#### Fixing backbone state dict

##### backbone from minerva

In [51]:
version = 'version_0'
file_path = f'training/ttsgan_minerva/{version}/checkpoints/'
ckpt_path = os.listdir(file_path)
print(ckpt_path)
ckpt = torch.load(file_path + ckpt_path[0])
ckpt['state_dict'].keys()

['epoch=299-step=276000.ckpt']


odict_keys(['gen.pos_embed', 'gen.l1.weight', 'gen.l1.bias', 'gen.blocks.0.0.fn.0.weight', 'gen.blocks.0.0.fn.0.bias', 'gen.blocks.0.0.fn.1.keys.weight', 'gen.blocks.0.0.fn.1.keys.bias', 'gen.blocks.0.0.fn.1.queries.weight', 'gen.blocks.0.0.fn.1.queries.bias', 'gen.blocks.0.0.fn.1.values.weight', 'gen.blocks.0.0.fn.1.values.bias', 'gen.blocks.0.0.fn.1.projection.weight', 'gen.blocks.0.0.fn.1.projection.bias', 'gen.blocks.0.1.fn.0.weight', 'gen.blocks.0.1.fn.0.bias', 'gen.blocks.0.1.fn.1.0.weight', 'gen.blocks.0.1.fn.1.0.bias', 'gen.blocks.0.1.fn.1.3.weight', 'gen.blocks.0.1.fn.1.3.bias', 'gen.blocks.1.0.fn.0.weight', 'gen.blocks.1.0.fn.0.bias', 'gen.blocks.1.0.fn.1.keys.weight', 'gen.blocks.1.0.fn.1.keys.bias', 'gen.blocks.1.0.fn.1.queries.weight', 'gen.blocks.1.0.fn.1.queries.bias', 'gen.blocks.1.0.fn.1.values.weight', 'gen.blocks.1.0.fn.1.values.bias', 'gen.blocks.1.0.fn.1.projection.weight', 'gen.blocks.1.0.fn.1.projection.bias', 'gen.blocks.1.1.fn.0.weight', 'gen.blocks.1.1.fn.0.bi

In [52]:
new_model = GAN(
        generator = TTSGAN_Generator(seq_len= 60, channels=6),
        discriminator = TTSGAN_Discriminator(seq_len=60, channels=6),
        loss_gen = torch.nn.BCELoss(),
        loss_dis = torch.nn.BCELoss(),
        )

new_model.load_state_dict(ckpt['state_dict'])
new_model.dis.state_dict().keys()


odict_keys(['backbone.0.cls_token', 'backbone.0.positions', 'backbone.0.projection.1.weight', 'backbone.0.projection.1.bias', 'backbone.1.0.0.fn.0.weight', 'backbone.1.0.0.fn.0.bias', 'backbone.1.0.0.fn.1.keys.weight', 'backbone.1.0.0.fn.1.keys.bias', 'backbone.1.0.0.fn.1.queries.weight', 'backbone.1.0.0.fn.1.queries.bias', 'backbone.1.0.0.fn.1.values.weight', 'backbone.1.0.0.fn.1.values.bias', 'backbone.1.0.0.fn.1.projection.weight', 'backbone.1.0.0.fn.1.projection.bias', 'backbone.1.0.1.fn.0.weight', 'backbone.1.0.1.fn.0.bias', 'backbone.1.0.1.fn.1.0.weight', 'backbone.1.0.1.fn.1.0.bias', 'backbone.1.0.1.fn.1.3.weight', 'backbone.1.0.1.fn.1.3.bias', 'backbone.1.1.0.fn.0.weight', 'backbone.1.1.0.fn.0.bias', 'backbone.1.1.0.fn.1.keys.weight', 'backbone.1.1.0.fn.1.keys.bias', 'backbone.1.1.0.fn.1.queries.weight', 'backbone.1.1.0.fn.1.queries.bias', 'backbone.1.1.0.fn.1.values.weight', 'backbone.1.1.0.fn.1.values.bias', 'backbone.1.1.0.fn.1.projection.weight', 'backbone.1.1.0.fn.1.projec

##### backbone from tts

In [158]:
ckpt_dir_path = f'../../logs/minerva/'
ckpt_list = os.listdir(ckpt_dir_path)
version = 3
ckpt = torch.load(f'{ckpt_dir_path + ckpt_list[version]}/Model/checkpoint')
print(f'current_path: {ckpt_dir_path + ckpt_list[version]}/Model/checkpoint')
ckpt['dis_state_dict'].keys()

current_path: ../../logs/minerva/UCI_DAGHAR_Multiclass_137694_D_60_6axis_2025_03_15_00_15_05/Model/checkpoint


odict_keys(['0.cls_token', '0.positions', '0.projection.1.weight', '0.projection.1.bias', '1.0.0.fn.0.weight', '1.0.0.fn.0.bias', '1.0.0.fn.1.keys.weight', '1.0.0.fn.1.keys.bias', '1.0.0.fn.1.queries.weight', '1.0.0.fn.1.queries.bias', '1.0.0.fn.1.values.weight', '1.0.0.fn.1.values.bias', '1.0.0.fn.1.projection.weight', '1.0.0.fn.1.projection.bias', '1.0.1.fn.0.weight', '1.0.1.fn.0.bias', '1.0.1.fn.1.0.weight', '1.0.1.fn.1.0.bias', '1.0.1.fn.1.3.weight', '1.0.1.fn.1.3.bias', '1.1.0.fn.0.weight', '1.1.0.fn.0.bias', '1.1.0.fn.1.keys.weight', '1.1.0.fn.1.keys.bias', '1.1.0.fn.1.queries.weight', '1.1.0.fn.1.queries.bias', '1.1.0.fn.1.values.weight', '1.1.0.fn.1.values.bias', '1.1.0.fn.1.projection.weight', '1.1.0.fn.1.projection.bias', '1.1.1.fn.0.weight', '1.1.1.fn.0.bias', '1.1.1.fn.1.0.weight', '1.1.1.fn.1.0.bias', '1.1.1.fn.1.3.weight', '1.1.1.fn.1.3.bias', '1.2.0.fn.0.weight', '1.2.0.fn.0.bias', '1.2.0.fn.1.keys.weight', '1.2.0.fn.1.keys.bias', '1.2.0.fn.1.queries.weight', '1.2.0.fn.1

In [166]:
ckpt['dis_state_dict']['0.cls_token'][0][0][0:10]

tensor([ 0.1454, -1.3598,  1.7254, -3.4696,  1.3015, -1.1387,  0.9746, -1.1433,
         0.4172,  0.0448], device='cuda:0')

New keys from dict should be:
['backbone.0.cls_token', 'backbone.0.positions', 'backbone.0.projection.1.weight', 'backbone.0.projection.1.bias', 'backbone.1.0.0.fn.0.weight', 'backbone.1.0.0.fn.0.bias', 'backbone.1.0.0.fn.1.keys.weight', 'backbone.1.0.0.fn.1.keys.bias', 'backbone.1.0.0.fn.1.queries.weight', 'backbone.1.0.0.fn.1.queries.bias', 'backbone.1.0.0.fn.1.values.weight', 'backbone.1.0.0.fn.1.values.bias', 'backbone.1.0.0.fn.1.projection.weight', 'backbone.1.0.0.fn.1.projection.bias', 'backbone.1.0.1.fn.0.weight', 'backbone.1.0.1.fn.0.bias', 'backbone.1.0.1.fn.1.0.weight', 'backbone.1.0.1.fn.1.0.bias', 'backbone.1.0.1.fn.1.3.weight', 'backbone.1.0.1.fn.1.3.bias', 'backbone.1.1.0.fn.0.weight', 'backbone.1.1.0.fn.0.bias', 'backbone.1.1.0.fn.1.keys.weight', 'backbone.1.1.0.fn.1.keys.bias', 'backbone.1.1.0.fn.1.queries.weight', 'backbone.1.1.0.fn.1.queries.bias', 'backbone.1.1.0.fn.1.values.weight', 'backbone.1.1.0.fn.1.values.bias', 'backbone.1.1.0.fn.1.projection.weight', 'backbone.1.1.0.fn.1.projection.bias', 'backbone.1.1.1.fn.0.weight', 'backbone.1.1.1.fn.0.bias', 'backbone.1.1.1.fn.1.0.weight', 'backbone.1.1.1.fn.1.0.bias', 'backbone.1.1.1.fn.1.3.weight', 'backbone.1.1.1.fn.1.3.bias', 'backbone.1.2.0.fn.0.weight', 'backbone.1.2.0.fn.0.bias', 'backbone.1.2.0.fn.1.keys.weight', 'backbone.1.2.0.fn.1.keys.bias', 'backbone.1.2.0.fn.1.queries.weight', 'backbone.1.2.0.fn.1.queries.bias', 'backbone.1.2.0.fn.1.values.weight', 'backbone.1.2.0.fn.1.values.bias', 'backbone.1.2.0.fn.1.projection.weight', 'backbone.1.2.0.fn.1.projection.bias', 'backbone.1.2.1.fn.0.weight', 'backbone.1.2.1.fn.0.bias', 'backbone.1.2.1.fn.1.0.weight', 'backbone.1.2.1.fn.1.0.bias', 'backbone.1.2.1.fn.1.3.weight', 'backbone.1.2.1.fn.1.3.bias', 'classification_head.clshead.1.weight', 'classification_head.clshead.1.bias', 'classification_head.clshead.2.weight', 'classification_head.clshead.2.bias']

old keys is:
['0.cls_token', '0.positions', '0.projection.1.weight', '0.projection.1.bias', '1.0.0.fn.0.weight', '1.0.0.fn.0.bias', '1.0.0.fn.1.keys.weight', '1.0.0.fn.1.keys.bias', '1.0.0.fn.1.queries.weight', '1.0.0.fn.1.queries.bias', '1.0.0.fn.1.values.weight', '1.0.0.fn.1.values.bias', '1.0.0.fn.1.projection.weight', '1.0.0.fn.1.projection.bias', '1.0.1.fn.0.weight', '1.0.1.fn.0.bias', '1.0.1.fn.1.0.weight', '1.0.1.fn.1.0.bias', '1.0.1.fn.1.3.weight', '1.0.1.fn.1.3.bias', '1.1.0.fn.0.weight', '1.1.0.fn.0.bias', '1.1.0.fn.1.keys.weight', '1.1.0.fn.1.keys.bias', '1.1.0.fn.1.queries.weight', '1.1.0.fn.1.queries.bias', '1.1.0.fn.1.values.weight', '1.1.0.fn.1.values.bias', '1.1.0.fn.1.projection.weight', '1.1.0.fn.1.projection.bias', '1.1.1.fn.0.weight', '1.1.1.fn.0.bias', '1.1.1.fn.1.0.weight', '1.1.1.fn.1.0.bias', '1.1.1.fn.1.3.weight', '1.1.1.fn.1.3.bias', '1.2.0.fn.0.weight', '1.2.0.fn.0.bias', '1.2.0.fn.1.keys.weight', '1.2.0.fn.1.keys.bias', '1.2.0.fn.1.queries.weight', '1.2.0.fn.1.queries.bias', '1.2.0.fn.1.values.weight', '1.2.0.fn.1.values.bias', '1.2.0.fn.1.projection.weight', '1.2.0.fn.1.projection.bias', '1.2.1.fn.0.weight', '1.2.1.fn.0.bias', '1.2.1.fn.1.0.weight', '1.2.1.fn.1.0.bias', '1.2.1.fn.1.3.weight', '1.2.1.fn.1.3.bias', '2.clshead.1.weight', '2.clshead.1.bias', '2.clshead.2.weight', '2.clshead.2.bias']

In [127]:
keys = ckpt["dis_state_dict"].keys()
print(f'original keys: {keys}')
new_ckpt = {'dis_state_dict': {}}

list_of_new_keys_in_order = ['backbone.0.cls_token', 'backbone.0.positions', 'backbone.0.projection.1.weight', 'backbone.0.projection.1.bias', 'backbone.1.0.0.fn.0.weight', 'backbone.1.0.0.fn.0.bias', 'backbone.1.0.0.fn.1.keys.weight', 'backbone.1.0.0.fn.1.keys.bias', 'backbone.1.0.0.fn.1.queries.weight', 'backbone.1.0.0.fn.1.queries.bias', 'backbone.1.0.0.fn.1.values.weight', 'backbone.1.0.0.fn.1.values.bias', 'backbone.1.0.0.fn.1.projection.weight', 'backbone.1.0.0.fn.1.projection.bias', 'backbone.1.0.1.fn.0.weight', 'backbone.1.0.1.fn.0.bias', 'backbone.1.0.1.fn.1.0.weight', 'backbone.1.0.1.fn.1.0.bias', 'backbone.1.0.1.fn.1.3.weight', 'backbone.1.0.1.fn.1.3.bias', 'backbone.1.1.0.fn.0.weight', 'backbone.1.1.0.fn.0.bias', 'backbone.1.1.0.fn.1.keys.weight', 'backbone.1.1.0.fn.1.keys.bias', 'backbone.1.1.0.fn.1.queries.weight', 'backbone.1.1.0.fn.1.queries.bias', 'backbone.1.1.0.fn.1.values.weight', 'backbone.1.1.0.fn.1.values.bias', 'backbone.1.1.0.fn.1.projection.weight', 'backbone.1.1.0.fn.1.projection.bias', 'backbone.1.1.1.fn.0.weight', 'backbone.1.1.1.fn.0.bias', 'backbone.1.1.1.fn.1.0.weight', 'backbone.1.1.1.fn.1.0.bias', 'backbone.1.1.1.fn.1.3.weight', 'backbone.1.1.1.fn.1.3.bias', 'backbone.1.2.0.fn.0.weight', 'backbone.1.2.0.fn.0.bias', 'backbone.1.2.0.fn.1.keys.weight', 'backbone.1.2.0.fn.1.keys.bias', 'backbone.1.2.0.fn.1.queries.weight', 'backbone.1.2.0.fn.1.queries.bias', 'backbone.1.2.0.fn.1.values.weight', 'backbone.1.2.0.fn.1.values.bias', 'backbone.1.2.0.fn.1.projection.weight', 'backbone.1.2.0.fn.1.projection.bias', 'backbone.1.2.1.fn.0.weight', 'backbone.1.2.1.fn.0.bias', 'backbone.1.2.1.fn.1.0.weight', 'backbone.1.2.1.fn.1.0.bias', 'backbone.1.2.1.fn.1.3.weight', 'backbone.1.2.1.fn.1.3.bias', 'classification_head.clshead.1.weight', 'classification_head.clshead.1.bias', 'classification_head.clshead.2.weight', 'classification_head.clshead.2.bias']
list_of_old_keys_in_order = ['0.cls_token', '0.positions', '0.projection.1.weight', '0.projection.1.bias', '1.0.0.fn.0.weight', '1.0.0.fn.0.bias', '1.0.0.fn.1.keys.weight', '1.0.0.fn.1.keys.bias', '1.0.0.fn.1.queries.weight', '1.0.0.fn.1.queries.bias', '1.0.0.fn.1.values.weight', '1.0.0.fn.1.values.bias', '1.0.0.fn.1.projection.weight', '1.0.0.fn.1.projection.bias', '1.0.1.fn.0.weight', '1.0.1.fn.0.bias', '1.0.1.fn.1.0.weight', '1.0.1.fn.1.0.bias', '1.0.1.fn.1.3.weight', '1.0.1.fn.1.3.bias', '1.1.0.fn.0.weight', '1.1.0.fn.0.bias', '1.1.0.fn.1.keys.weight', '1.1.0.fn.1.keys.bias', '1.1.0.fn.1.queries.weight', '1.1.0.fn.1.queries.bias', '1.1.0.fn.1.values.weight', '1.1.0.fn.1.values.bias', '1.1.0.fn.1.projection.weight', '1.1.0.fn.1.projection.bias', '1.1.1.fn.0.weight', '1.1.1.fn.0.bias', '1.1.1.fn.1.0.weight', '1.1.1.fn.1.0.bias', '1.1.1.fn.1.3.weight', '1.1.1.fn.1.3.bias', '1.2.0.fn.0.weight', '1.2.0.fn.0.bias', '1.2.0.fn.1.keys.weight', '1.2.0.fn.1.keys.bias', '1.2.0.fn.1.queries.weight', '1.2.0.fn.1.queries.bias', '1.2.0.fn.1.values.weight', '1.2.0.fn.1.values.bias', '1.2.0.fn.1.projection.weight', '1.2.0.fn.1.projection.bias', '1.2.1.fn.0.weight', '1.2.1.fn.0.bias', '1.2.1.fn.1.0.weight', '1.2.1.fn.1.0.bias', '1.2.1.fn.1.3.weight', '1.2.1.fn.1.3.bias', '2.clshead.1.weight', '2.clshead.1.bias', '2.clshead.2.weight', '2.clshead.2.bias']
for i, key in enumerate(keys):
    new_key = list_of_new_keys_in_order[i]
    new_ckpt['dis_state_dict'][new_key] = ckpt['dis_state_dict'][key]

print(f'after key check: {new_ckpt["dis_state_dict"].keys()}')
print(f'\nare they compatible with the model now? {list(new_ckpt["dis_state_dict"].keys()) == list(new_model.dis.state_dict().keys())}')

if os.path.isdir(f'backbones/{version}') == False:
    os.mkdir(f'backbones/{version}')
torch.save(new_ckpt, f'backbones/{version}/model.pth')
print('done')

original keys: odict_keys(['0.cls_token', '0.positions', '0.projection.1.weight', '0.projection.1.bias', '1.0.0.fn.0.weight', '1.0.0.fn.0.bias', '1.0.0.fn.1.keys.weight', '1.0.0.fn.1.keys.bias', '1.0.0.fn.1.queries.weight', '1.0.0.fn.1.queries.bias', '1.0.0.fn.1.values.weight', '1.0.0.fn.1.values.bias', '1.0.0.fn.1.projection.weight', '1.0.0.fn.1.projection.bias', '1.0.1.fn.0.weight', '1.0.1.fn.0.bias', '1.0.1.fn.1.0.weight', '1.0.1.fn.1.0.bias', '1.0.1.fn.1.3.weight', '1.0.1.fn.1.3.bias', '1.1.0.fn.0.weight', '1.1.0.fn.0.bias', '1.1.0.fn.1.keys.weight', '1.1.0.fn.1.keys.bias', '1.1.0.fn.1.queries.weight', '1.1.0.fn.1.queries.bias', '1.1.0.fn.1.values.weight', '1.1.0.fn.1.values.bias', '1.1.0.fn.1.projection.weight', '1.1.0.fn.1.projection.bias', '1.1.1.fn.0.weight', '1.1.1.fn.0.bias', '1.1.1.fn.1.0.weight', '1.1.1.fn.1.0.bias', '1.1.1.fn.1.3.weight', '1.1.1.fn.1.3.bias', '1.2.0.fn.0.weight', '1.2.0.fn.0.bias', '1.2.0.fn.1.keys.weight', '1.2.0.fn.1.keys.bias', '1.2.0.fn.1.queries.weigh

In [147]:
ckpt['dis_state_dict']

OrderedDict([('0.cls_token',
              tensor([[[ 0.1454, -1.3598,  1.7254, -3.4696,  1.3015, -1.1387,  0.9746,
                        -1.1433,  0.4172,  0.0448,  2.0279,  2.0138,  0.3544, -0.4625,
                        -1.1856,  0.0087, -0.4812, -0.9220, -0.3195,  0.7474,  0.0312,
                         0.9211, -0.3176, -0.9459, -0.7639,  0.4222, -0.2308, -0.1434,
                        -0.1691, -0.1000, -1.7205, -0.3449, -1.2839, -1.1646,  1.0659,
                        -2.3886,  1.1418,  0.7263,  0.8932,  0.4898,  1.9029, -0.0714,
                         0.1271, -1.1270, -1.3112, -0.4967,  0.8090, -1.5684, -1.5039,
                         1.0001]]], device='cuda:0')),
             ('0.positions',
              tensor([[-1.6029, -3.1253,  0.2231, -3.0570, -0.4390,  0.3491, -0.1609, -0.3252,
                        1.0401,  0.9092,  0.9704, -1.3778,  1.0102,  0.7771, -0.5664, -1.7390,
                       -1.0201,  0.9447, -0.1667, -0.6467, -2.8363,  0.7149,  0.4378,  0

In [ ]:
new_ckpt['dis_state_dict']

{'backbone.0.cls_token': tensor([[[ 0.1454, -1.3598,  1.7254, -3.4696,  1.3015, -1.1387,  0.9746,
           -1.1433,  0.4172,  0.0448,  2.0279,  2.0138,  0.3544, -0.4625,
           -1.1856,  0.0087, -0.4812, -0.9220, -0.3195,  0.7474,  0.0312,
            0.9211, -0.3176, -0.9459, -0.7639,  0.4222, -0.2308, -0.1434,
           -0.1691, -0.1000, -1.7205, -0.3449, -1.2839, -1.1646,  1.0659,
           -2.3886,  1.1418,  0.7263,  0.8932,  0.4898,  1.9029, -0.0714,
            0.1271, -1.1270, -1.3112, -0.4967,  0.8090, -1.5684, -1.5039,
            1.0001]]], device='cuda:0'),
 'backbone.0.positions': tensor([[-1.6029, -3.1253,  0.2231, -3.0570, -0.4390,  0.3491, -0.1609, -0.3252,
           1.0401,  0.9092,  0.9704, -1.3778,  1.0102,  0.7771, -0.5664, -1.7390,
          -1.0201,  0.9447, -0.1667, -0.6467, -2.8363,  0.7149,  0.4378,  0.8654,
           0.4759, -0.1527, -0.9691, -1.5958,  0.6147, -0.6126,  1.1625,  1.6831,
          -0.0284, -0.2878, -0.4598, -1.2840,  1.0653,  1.6282,  